# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Iain Nash
description: >- # this means to ignore newlines until "baseurl:"
  iain is a multidiscipliary engineer
  focused on the intersections of
  machines and humans
  these interested are manifested in
  full-stack engineering at oscar health
  building immersive experiences and events
  and prototyping iot and wearable devices
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://iain.in/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: isiain
github_username:  iainnash

# Build settings
markdown: kramdown

collections:
  - career
  - interactive
  - teaching

defaults:
  - scope:
      path: ""
      type: "career"
    values:
      layout: career_item
  - scope:
      path: ""
      type: "interactive"
    values:
      layout: interactive_item

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
